import secureLocalStorage from "react-secure-storage";
import { STORAGE_INDEXES } from "../constants";

export function defaultInitialState(LOCAL_STORAGE_KEY, token = null) {
  let DEFAULT_INITIAL_STATES = {};
  DEFAULT_INITIAL_STATES[STORAGE_INDEXES.IS_AUTHENTICATED] = false;
  DEFAULT_INITIAL_STATES[STORAGE_INDEXES.EMAIL] = null;
  DEFAULT_INITIAL_STATES[STORAGE_INDEXES.NAME] = null;
  DEFAULT_INITIAL_STATES[STORAGE_INDEXES.ACCESS_TOKEN] = token;
  DEFAULT_INITIAL_STATES[STORAGE_INDEXES.FIRST_NAME] = null;
  DEFAULT_INITIAL_STATES[STORAGE_INDEXES.LAST_NAME] = null;
  DEFAULT_INITIAL_STATES[STORAGE_INDEXES.USERNAME] = null;
  DEFAULT_INITIAL_STATES[STORAGE_INDEXES.USER_ID] = null;
  DEFAULT_INITIAL_STATES[STORAGE_INDEXES.IS_VERFIED] = null;
  DEFAULT_INITIAL_STATES[STORAGE_INDEXES.IS_ACTIVE] = null;
  DEFAULT_INITIAL_STATES[STORAGE_INDEXES.PROFILE_PICTURE] = null;
  let APP_SETTINGS = {};
  APP_SETTINGS[STORAGE_INDEXES.ROLE_LIST] = {};
  DEFAULT_INITIAL_STATES[STORAGE_INDEXES.APP_SETTINGS] = APP_SETTINGS;
  if (typeof window !== "undefined") {
    secureLocalStorage.setItem(
      LOCAL_STORAGE_KEY,
      JSON.stringify(DEFAULT_INITIAL_STATES)
    );
  }

  return DEFAULT_INITIAL_STATES;
}

export function loginFailure(errorMessage) {
  let AUTH_USER_DATA = {};
  AUTH_USER_DATA[STORAGE_INDEXES.IS_AUTHENTICATED] = false;
  AUTH_USER_DATA[STORAGE_INDEXES.LOADER] = false;
  AUTH_USER_DATA[STORAGE_INDEXES.EMAIL] = null;
  AUTH_USER_DATA[STORAGE_INDEXES.ACCESS_TOKEN] = null;
  AUTH_USER_DATA[STORAGE_INDEXES.NAME] = null;
  AUTH_USER_DATA[STORAGE_INDEXES.ERROR_MESSAGE] = { auth: errorMessage };
  AUTH_USER_DATA[STORAGE_INDEXES.USER_ID] = 0;
  AUTH_USER_DATA[STORAGE_INDEXES.USER_ROLE] = null;
  return AUTH_USER_DATA;
}

export function authUserData(data) {
  const {
    id,
    is_active,
    isVerified,
    name,
    profile_picture,
    access_token,
    lastName,
    firstName,
    email,
    company_name,
    public_api_key,
    isSubscribed,
    userSector,
    userSubSector,
  } = data;

  let AUTH_USER_DATA = {};
  AUTH_USER_DATA[STORAGE_INDEXES.IS_AUTHENTICATED] = true;
  AUTH_USER_DATA[STORAGE_INDEXES.EMAIL] = email;
  AUTH_USER_DATA[STORAGE_INDEXES.NAME] = name;
  AUTH_USER_DATA[STORAGE_INDEXES.FIRST_NAME] = firstName;
  AUTH_USER_DATA[STORAGE_INDEXES.LAST_NAME] = lastName;
  AUTH_USER_DATA[STORAGE_INDEXES.USERNAME] = name;
  AUTH_USER_DATA[STORAGE_INDEXES.USER_ID] = id;
  AUTH_USER_DATA[STORAGE_INDEXES.IS_VERFIED] = isVerified;
  AUTH_USER_DATA[STORAGE_INDEXES.ACCESS_TOKEN] = access_token;
  AUTH_USER_DATA[STORAGE_INDEXES.IS_ACTIVE] = is_active;
  AUTH_USER_DATA[STORAGE_INDEXES.COMPANY_NAME] = company_name;
  AUTH_USER_DATA[STORAGE_INDEXES.PUBLIC_API_KEY] = public_api_key;
  AUTH_USER_DATA[STORAGE_INDEXES.PROFILE_PICTURE] = profile_picture || null;
  AUTH_USER_DATA[STORAGE_INDEXES.SUBSCRIBED] = isSubscribed;
  AUTH_USER_DATA[STORAGE_INDEXES.USER_SECTOR] = userSector;
  AUTH_USER_DATA[STORAGE_INDEXES.USER_SUB_SECTOR] = userSubSector;

  return AUTH_USER_DATA;
}
